maximum_availability_zones: 5

# cluster name is prefixed with environment name
# cluster_name: cluster

# ecs_extra_tags:
#   Name: Value

ecs_agent_extra_config:
  ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION: 10m
  ECS_IMAGE_CLEANUP_INTERVAL: 10m
  ECS_IMAGE_MINIMUM_CLEANUP_AGE: 5m

# asg_update_policy:
#   AutoScalingRollingUpdate:
#     MaxBatchSize: 1
#     MinInstancesInService: 1
#     SuspendProcesses: ["HealthCheck","ReplaceUnhealthy","AZRebalance","AlarmNotification","ScheduledActions"]


component_version: 0.0.1
log_group_retention: 14

enable_efs: true

iam_policies:
  ecs-container-instance:
    action:
      - ecs:CreateCluster
      - ecs:DeregisterContainerInstance
      - ecs:DiscoverPollEndpoint
      - ecs:Poll
      - ecs:RegisterContainerInstance
      - ecs:StartTelemetrySession
      - ecs:Submit*
      - ecr:GetAuthorizationToken
      - ecr:BatchCheckLayerAvailability
      - ecr:GetDownloadUrlForLayer
      - ecr:BatchGetImage
      - logs:CreateLogStream
      - logs:PutLogEvents
